name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet
        run: nuget restore

      - name: Build
        run: msbuild charms-bar-port.sln /p:Configuration=Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: charms-bar
          path: |
            **/bin/Release/**
